extern const GeoLayout wing_cap_dew_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout wing_cap_dew_geo[];
extern Lights1 wing_cap_dew_frame_lights;
extern Lights1 wing_cap_dew_glasses_lights;
extern u8 wing_cap_dew_wing1_rgba16[];
extern u8 wing_cap_dew_wing_2_rgba16[];
extern u8 wing_cap_dew_glassestex_rgba16[];
extern Vtx wing_cap_dew_Wing_Cap_DL_mesh_layer_4_vtx_0[8];
extern Gfx wing_cap_dew_Wing_Cap_DL_mesh_layer_4_tri_0[];
extern Vtx wing_cap_dew_Wing_Cap_DL_mesh_layer_4_vtx_1[8];
extern Gfx wing_cap_dew_Wing_Cap_DL_mesh_layer_4_tri_1[];
extern Vtx wing_cap_dew_Wing_Cap_DL_mesh_layer_1_vtx_0[550];
extern Gfx wing_cap_dew_Wing_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx wing_cap_dew_Wing_Cap_DL_mesh_layer_1_vtx_1[18];
extern Gfx wing_cap_dew_Wing_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_wing_cap_dew_Wing_Base[];
extern Gfx mat_revert_wing_cap_dew_Wing_Base[];
extern Gfx mat_wing_cap_dew_Wing_Tip[];
extern Gfx mat_revert_wing_cap_dew_Wing_Tip[];
extern Gfx mat_wing_cap_dew_frame[];
extern Gfx mat_revert_wing_cap_dew_frame[];
extern Gfx mat_wing_cap_dew_glasses[];
extern Gfx mat_revert_wing_cap_dew_glasses[];
extern Gfx wing_cap_dew_Wing_Cap_DL_mesh_layer_4[];
extern Gfx wing_cap_dew_Wing_Cap_DL_mesh_layer_1[];
extern Gfx wing_cap_dew_material_revert_render_settings[];
