extern const GeoLayout normal_dew_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout normal_dew_geo[];
extern Lights1 normal_dew_frame_lights;
extern Lights1 normal_dew_glasses_lights;
extern u8 normal_dew_glassestex_rgba16[];
extern Vtx normal_dew_Cap_DL_mesh_layer_1_vtx_0[550];
extern Gfx normal_dew_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx normal_dew_Cap_DL_mesh_layer_1_vtx_1[18];
extern Gfx normal_dew_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_normal_dew_frame[];
extern Gfx mat_revert_normal_dew_frame[];
extern Gfx mat_normal_dew_glasses[];
extern Gfx mat_revert_normal_dew_glasses[];
extern Gfx normal_dew_Cap_DL_mesh_layer_1[];
extern Gfx normal_dew_material_revert_render_settings[];
