extern const GeoLayout metalwing_cap_dt_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout metalwing_cap_dt_geo[];
extern Lights1 metalwing_cap_dt_clip_lights;
extern u8 metalwing_cap_dt_wing1_rgba16[];
extern u8 metalwing_cap_dt_wing_2_rgba16[];
extern u8 metalwing_cap_dt_CLIP_rgba16[];
extern Vtx metalwing_cap_dt_Winged_Metal_Cap_DL_mesh_layer_4_vtx_0[8];
extern Gfx metalwing_cap_dt_Winged_Metal_Cap_DL_mesh_layer_4_tri_0[];
extern Vtx metalwing_cap_dt_Winged_Metal_Cap_DL_mesh_layer_4_vtx_1[8];
extern Gfx metalwing_cap_dt_Winged_Metal_Cap_DL_mesh_layer_4_tri_1[];
extern Vtx metalwing_cap_dt_Winged_Metal_Cap_DL_mesh_layer_1_vtx_0[32];
extern Gfx metalwing_cap_dt_Winged_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Gfx mat_metalwing_cap_dt_Wing_Base[];
extern Gfx mat_revert_metalwing_cap_dt_Wing_Base[];
extern Gfx mat_metalwing_cap_dt_Wing_Tip[];
extern Gfx mat_revert_metalwing_cap_dt_Wing_Tip[];
extern Gfx mat_metalwing_cap_dt_clip[];
extern Gfx mat_revert_metalwing_cap_dt_clip[];
extern Gfx metalwing_cap_dt_Winged_Metal_Cap_DL_mesh_layer_4[];
extern Gfx metalwing_cap_dt_Winged_Metal_Cap_DL_mesh_layer_1[];
extern Gfx metalwing_cap_dt_material_revert_render_settings[];
